"""Parse first batch of Dribbble shots from snapshot data."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.ingest_dribbble import ingest_shots

# Extracted from browser snapshot of Dribbble search "dashboard dark mode"
shots = [
    {"title": "AI-Powered Modern Business Dashboard UI UX Design.", "tags": "admin panel ui ai assistant ui ai powered dashboard analytics dashboard ui automation dashboard business analytics dashboard dark mode dashboard dashboard ui dashboard ux data visualization ui enterprise dashboard futuristic dashboard design kpi dashboard ui minimal dashboard design modern dashboard design productivity dashboard professional dashboard uiux saas dashboard ui smart dashboard concept web app dashboard", "url": "/shots/26565558-AI-Powered-Modern-Business-Dashboard-UI-UX-Design", "designer": "Nazrul Islam Raihan", "likes": "33", "views": "12.2k"},
    {"title": "Project Monitoring Dashboard Interface Dark Mode - Manageryo", "tags": "blue chart chart dashboard dark mode dark mode dashboard dashboard design employee dashboard ui modern design ui monitoring dashboard ux project management uiux project monitoring ui project tracking dashboard saas dashboard task ui uiux ux web ui web ux", "url": "/shots/24468365-Project-Monitoring-Dashboard-Interface-Dark-Mode-Manageryo", "designer": "Gidion Bagas Prananta", "likes": "88", "views": "17.2k"},
    {"title": "Sales Analytics Dashboard (Dark mode)", "tags": "analytics dashbaord b2b dashboard dashboard app dashboard ui database ecommerce ecommerce sales marketing dashboard modern product design sales analytics sales marketing dashbaord sales performance sales report sass sass dashboard tablet uiux web app", "url": "/shots/25770479-Sales-Analytics-Dashboard-Dark-mode", "designer": "Anna Zhou", "likes": "23", "views": "8.6k"},
    {"title": "Shown AI - Dark mode - Dashboard", "tags": "ad campaign ads ads manager analytics builder campaigns card charts dark dark mode dashboard list marketing dashboard menu navigation price reports sidebar social media statistics", "url": "/shots/25541330-Shown-AI-Dark-mode-Dashboard", "designer": "Juliette Lagache", "likes": "163", "views": "52.7k"},
    {"title": "Coinstax: Crypto Transactions - Dark Mode", "tags": "bitcoin dashboard blockchain dashboard coinstax crypto dashboard crypto transaction crypto transactions cryptocurrency dashboard dark dashboard dark mode dashboard dark theme dashboard modern dashboard popular trending ui ui design user interface ux ux design web3 dashboard", "url": "/shots/25477618-Coinstax-Crypto-Transactions-Dark-Mode", "designer": "Rizki Mulyawan", "likes": "61", "views": "15.9k"},
    {"title": "SaaS Dark mode dashboard", "tags": "design figma ui", "url": "/shots/26676679-SaaS-Dark-mode-dashboard", "designer": "Leandro Ubilla", "likes": "11", "views": "3.2k"},
    {"title": "Crypto Dashboard - Dark Mode", "tags": "branding card crypto cryptocurrency dark mode dashboard data exchange gradient graphic design layout light responsive stats transactions typography ui website whitespace", "url": "/shots/26123474-Crypto-Dashboard-Dark-Mode", "designer": "Paperpillar", "likes": "162", "views": "52.4k"},
    {"title": "Bandwidth Management dark mode Dashboard - concept design", "tags": "app design bandwidth concept darkmode dashboard desktop minimalist navy", "url": "/shots/19797577-Bandwidth-Management-dark-mode-Dashboard-concept-design", "designer": "Merixstudio", "likes": "55", "views": "15.2k"},
    {"title": "Dark mode dashboard - Bookings table", "tags": "app dark ui dashboard design filters skeumorphism skeuomorph table ui ux web", "url": "/shots/15468781-Dark-mode-dashboard-Bookings-table", "designer": "Ohad Peled", "likes": "33", "views": "18.2k"},
    {"title": "NexusAI - Conversational AI & Agent Platform Dashboard", "tags": "admin panel ai agent ai interface concept design conversational ui dark mode dashboard ui deep learning figma gpt minimal ui modern ui productivity app saas sleek design technology ui design ux design web app workflow automation", "url": "/shots/26707358-NexusAI-Conversational-AI-Agent-Platform-Dashboard", "designer": "Lingesh Chary", "likes": "9", "views": "4.1k"},
    {"title": "Task Management Web App UI - Kanban Board, Timeline, Calendar", "tags": "asana board view ui calendar scheduling ui clickup dark mode dashboard dashboard design kanban board ui left sidebar navigation multi project workspace priority labels ui productivity saas ui project management dashboard status chips ui task card design task management web app team collaboration ui timeline view ui ux ui design web app ui workspace", "url": "/shots/26697852-Task-Management-Web-App-UI-Kanban-Board-Timeline-Calendar", "designer": "Vislume Studio", "likes": "85", "views": "35.8k"},
    {"title": "Dark Mode Dashboard - AI Marketing Analytics Design", "tags": "aiinterface creativedashboard darkmodeui dashboarddesign datavisualization designsystem digitaldesign figmadesign interfacedesign madeinfigma minimaldesign modernui productdesign techdesign ui uidesign userinterface uxdesign uxuidesign webappdesign", "url": "/shots/26727175-Dark-Mode-Dashboard-AI-Marketing-Analytics-Design", "designer": "Safiul Alam", "likes": "3", "views": "3.3k"},
    {"title": "Body Wallet - Dark mode Dashboard", "tags": "crypto crypto wallet dashboard design productdesign ui user interface wallet web3", "url": "/shots/24649752-Body-Wallet-Dark-mode-Dashboard", "designer": "Isdehghan", "likes": "24", "views": "3.6k"},
    {"title": "Coinstax: Market Details - Dark Mode", "tags": "bitcoin dashboard charts dashboard clean dark mode clean web app coinstax crypto dashboard crypto markets crypto overview crypto portfolio dashboard crypto web app dark mode dashboard dark theme dashboard fintech fintech dashboard ui ui design user interface web3 web3 app web3 dashboard", "url": "/shots/25812701-Coinstax-Market-Details-Dark-Mode", "designer": "Rizki Mulyawan", "likes": "32", "views": "12.8k"},
    {"title": "Connect360 - CRM Business Partner Dashboard Darkmode Version", "tags": "activity admin b2b crm darkmode darkmode dashboard dashboard dashboard crm data management management sales dashboard ui ux website crm", "url": "/shots/25577408-Connect360-CRM-Business-Partner-Dashboard-Darkmode-Version", "designer": "Keitoto", "likes": "135", "views": "22k"},
    {"title": "Crypto dark mode dashboard - concept", "tags": "assets bitcoin candle candlestick chart crypto currency dark dashboard ethereum minimal mode piechart sparkline trading wallet", "url": "/shots/18254243-Crypto-dark-mode-dashboard-concept", "designer": "Merixstudio", "likes": "123", "views": "33.1k"},
    {"title": "Botly - AI Chatbot Dashboard - Dark Mode", "tags": "3d 3d character 3d illustration chart clean dashboard illustration minimal pie chart progress sidebar template ui ui design ux ux design web web design web template website", "url": "/shots/22079049-Botly-AI-Chatbot-Dashboard-Dark-Mode", "designer": "Tran Mau Tri Tam", "likes": "434", "views": "160k"},
    {"title": "User Management Dashboard - Dark Mode", "tags": "dark mode dashboard dashboard design dashboard figma dashboard template dashboard ui dashboard ui concept dashboard ui design dashboard ui design project dashboard ui kit database filter saas status management table user management", "url": "/shots/25748099-User-Management-Dashboard-Dark-Mode", "designer": "Dmitry Sergushkin", "likes": "78", "views": "45.7k"},
    {"title": "ManyCrypto - Dashboard Dark Mode", "tags": "bitcoin chart clean crypto cryptocurrency dashboard dark dark mode dashboard data design flat graph interface minimal minimalist statistics ui ux web website", "url": "/shots/16971369-ManyCrypto-Dashboard-Dark-Mode", "designer": "Enver Studio", "likes": "364", "views": "113k"},
    {"title": "Crypto Dashboard | Dark Mode Design", "tags": "analytics crypto dashboard cryptocurrency ethereum pool dasboard product design trading platform wallet dashboard web3 dashboard", "url": "/shots/26667452-Crypto-Dashboard-Dark-Mode-Design", "designer": "Jumatechs", "likes": "70", "views": "4.3k"},
    {"title": "Floney - Fintech Dashboard Dark Mode", "tags": "components dark dark app dark mode dark theme dark ui dashboard data dashboard interface mode night mode payment dashboard payment gateway saas saas menu saas sidebar scoring settings dark statistics", "url": "/shots/24260837-Floney-Fintech-Dashboard-Dark-Mode", "designer": "Nija Works", "likes": "77", "views": "27.1k"},
    {"title": "Chatty - Message Dashboard [ Dark Mode ]", "tags": "chat chat dashboard chatting community dark darkmode dashboard dashboard design group chat message message dashboard product product design whatsapp", "url": "/shots/21238750-Chatty-Message-Dashboard-Dark-Mode", "designer": "Hatypo Studio", "likes": "152", "views": "38.8k"},
    {"title": "Dashboard - Dark mode", "tags": "app dark mode dashboard design system form inputs interface product design ui ux", "url": "/shots/16755965-Dashboard-Dark-mode", "designer": "Amondo", "likes": "87", "views": "53.2k"},
    {"title": "Job Finder Responsive Dashboard - Dark Mode", "tags": "app application apply dark dark mode dark mode dashboard dashboard dashboard ui finder job job finder mobile mobile mobile design mobile ui responsive search ui user experience user interface ux", "url": "/shots/23616488-Job-Finder-Responsive-Dashboard-Dark-Mode", "designer": "George Chichua", "likes": "70", "views": "13.2k"},
    {"title": "Crypto Exchange Dashboard - Dark mode", "tags": "3d bitcoin blockchain branding chart coin crypto cryptocurrency dark darkmode dashboard design exchange financial illustration landing ui ux visualdesign website", "url": "/shots/18838509-Crypto-Exchange-Dashboard-Dark-mode", "designer": "Oniex", "likes": "167", "views": "17k"},
    {"title": "Cryven Crypto Dashboard - Dark Mode Trading & Wallet UI Design", "tags": "blockchain design clean design crypto crypto dashboard crypto exchange crypto wallet dark mode dashboard ui data visualization finance app fintech fintech design modern interface saas dashboard trading app uiux uiux designer web app", "url": "/shots/26749742-Cryven-Crypto-Dashboard-Dark-Mode-Trading-Wallet-UI-Design", "designer": "Musemind", "likes": "163", "views": "17.6k"},
    {"title": "Dashboard Darkmode To do List", "tags": "b2b b2c cansaas clean dark mode dashboard dashbor design interface minimal product design productivity saas task task management task manager to do to do list ui ux", "url": "/shots/24986666-Dashboard-Darkmode-To-do-List", "designer": "Cansaas", "likes": "53", "views": "8.7k"},
    {"title": "Leadora - Lead Scoring Dashboard Dark Mode", "tags": "automationdashboard b2b dark mode dark theme dark ui dashboard dashboard dark mode lead dashboard lead management lead scoring leads leads scoring dashboard marketing dashboard performance tracking saas saas product saas sidebar scoring settings dark ui", "url": "/shots/26732502-Leadora-Lead-Scoring-Dashboard-Dark-Mode", "designer": "Nija Works", "likes": "32", "views": "5.1k"},
    {"title": "AI SaaS Dashboard - Dark Mode", "tags": "ai ai chat ai design ai saas chat bot dark mode dashboard kanban kanban dashboard kanban ui product design project management saas chat saas design task management task manager tasks ui chat ui dashboard web app", "url": "/shots/25825708-AI-SaaS-Dashboard-Dark-Mode", "designer": "Robert Licau", "likes": "242", "views": "35.3k"},
    {"title": "Finor Dashboard | Dark Mode Finance Management UI Design", "tags": "analytics dashboard banking dashboard clean interface dark mode dashboard ui data visualization finance app fintech design modern ui product design saas dashboard uiux uiux designer user experience web app", "url": "/shots/26739883-Finor-Dashboard-Dark-Mode-Finance-Management-UI-Design", "designer": "Musemind", "likes": "143", "views": "10.7k"},
    {"title": "Card Dashboard | Dark Mode Fintech Banking App", "tags": "analytics dashboard banking app card dashboard clean ui dark mode finance app finance dashboard fintech modern ui payment app product design transaction ui ui design wallet app web app", "url": "/shots/26793064-Card-Dashboard-Dark-Mode-Fintech-Banking-App", "designer": "Musemind", "likes": "120", "views": "12.4k"},
    {"title": "Aerolytic - Sales Analytics Dashboard Darkmode Version", "tags": "activity analytic app design chart crm darkmode darkmode dashboard dashboard dashboard app finance finance dashboard order product product app saas saas dashboard sales sales dashboard ui design ux design", "url": "/shots/25708278-Aerolytic-Sales-Analytics-Dashboard-Darkmode-Version", "designer": "Keitoto", "likes": "81", "views": "21k"},
    {"title": "Task management: to do list dashboard (Dark mode)", "tags": "app app design clean components dark mode dashboard design interface minimal mobile platform task management tasks to do list ui ui design ux ux design web web design", "url": "/shots/18356550-Task-management-to-do-list-dashboard-Dark-mode", "designer": "Mehdi Bagheri", "likes": "640", "views": "260k"},
    {"title": "Task Management Dashboard (Dark Mode)", "tags": "clean dark dark mode dark saas dark website design dsahboard saas saas app software task task app task management ui uidesign uidesigner uiux uiuxdesign userinterface web app", "url": "/shots/23866530-Task-Management-Dashboard-Dark-Mode", "designer": "Nuha Maulana Ahsan", "likes": "31", "views": "10.5k"},
    {"title": "Sales Dashboard - Dark Mode", "tags": "analytic charts clean ui crm dashboard graphs line chart marketing report saas sales sales dashboard table ui user interface ux ux design", "url": "/shots/20398432-Sales-Dashboard-Dark-Mode", "designer": "Aynaz", "likes": "166", "views": "48k"},
    {"title": "Task Management - Dashboard Dark Mode Version", "tags": "clean clean dashboard dark mode dashboard design ios manage management app manager minimal minimalist mobile saas task task dashboard management task list task management tasks team ui", "url": "/shots/17876949--Task-Management-Dashboard-Dark-Mode-Version", "designer": "Enver Studio", "likes": "238", "views": "76.6k"},
]

ingest_shots(shots, "dashboard-dark-mode")
