"""Parse Dribbble pricing page shots."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from scripts.ingest_dribbble import ingest_shots

shots = [
    {"title": "Pricing Page - Saas Stock Investment", "tags": "card clean comparison darkmode design inner page investment market minimalist plans pricing card pricing plan pricing section saas section stock ui ux web design website", "url": "/shots/25812310-Pricing-Page-Saas-Stock-Investment", "designer": "Ali Husni", "likes": "163", "views": "40.3k"},
    {"title": "Pricing Page - SaaS Finance Website", "tags": "clean darkmode design finance management finance platform fintech fintech platform inner page landing page minimalist price pricing card pricing page pricing plan pricing section saas saas website ui ux web design", "url": "/shots/24180428-Pricing-Page-SaaS-Finance-Website", "designer": "Ali Husni", "likes": "339", "views": "139k"},
    {"title": "Pricing Page - SaaS Platform", "tags": "enterprise form interface landing lp page platform pricing saas standard subscribe", "url": "/shots/25171755-Pricing-Page-SaaS-Platform", "designer": "Max Zlydar", "likes": "3", "views": "1.3k"},
    {"title": "Pricing Page - SaaS Website Design", "tags": "ai homepage ai saas website chatbot landing page conversational ai website landing page price card price compare pricing page saas landing page saas website design uiux", "url": "/shots/25292729-Pricing-Page-SaaS-Website-Design", "designer": "Foyez Ahmed Kawsar", "likes": "26", "views": "16.3k"},
    {"title": "Call AI Sales Automation Platforms", "tags": "ai saas call platform ai saas dashboard ai saas website ai web app design branding call center platform crm dashboard design interface product saas service startup ui ux web app web design", "url": "/shots/26732774-Call-AI-Sales-Automation-Platforms", "designer": "Wavespace", "likes": "61", "views": "11.9k"},
    {"title": "Pricing Pages - Xmars SAAS Website", "tags": "agency b2b business clean company compare plans design framer pricing page pricing table saas simple team technology web design webflow", "url": "/shots/26976802-Pricing-Pages-Xmars-SAAS-Website", "designer": "Vektora", "likes": "95", "views": "10.5k"},
    {"title": "Pricing page for SaaS Fintech Landing Page", "tags": "clean dark mode design finance fintech fintech platform landing page plans price pricing pricing page product design saas ui ux website", "url": "/shots/24853339-Pricing-page-for-SaaS-Fintech-Landing-Page", "designer": "Keitoto", "likes": "167", "views": "43.3k"},
    {"title": "SaaS Pricing Page", "tags": "interface landing landing page minimalist modern pricing pricing page pricing table saas ui ux web design web pricing", "url": "/shots/22276265-SaaS-Pricing-Page", "designer": "Odama", "likes": "732", "views": "272k"},
    {"title": "E-commerce SaaS Pricing Page Design", "tags": "ecommerce landing page ecommerce saas design landing page management app pricing section product design saas subscription page web design website design", "url": "/shots/27088603-E-commerce-SaaS-Pricing-Page-Design", "designer": "Fixoria Studio", "likes": "124", "views": "8k"},
    {"title": "AI SaaS Pricing Page UI", "tags": "ai website card ui design pricing cards pricing page pricing table product saas pricing saas website subscription ui web", "url": "/shots/27064598-AI-SaaS-Pricing-Page-UI", "designer": "Alamin Hossen", "likes": "135", "views": "12.5k"},
    {"title": "Motta - Saas Pricing Page", "tags": "button card dark monthly plans pricing pricing table saas saas design saas featured saas frontend saas landingpage saas page saas website ui element user interface yearly", "url": "/shots/22732928-Motta-Saas-Pricing-Page", "designer": "Pixelz", "likes": "1", "views": "115k"},
    {"title": "Pricing + Company Page Pine SaaS Template", "tags": "black card design company design pine pricing pricing app pricing page saas saas design saas template template typography ui ux yellow", "url": "/shots/16811044-Pricing-Company-Page-Pine-SaaS-Template", "designer": "Flowbase", "likes": "537", "views": "166k"},
    {"title": "Saas Pricing Page", "tags": "b2b business cansaas clean design interface landing page pricing saas saas websites ui ux web design websites", "url": "/shots/24786235-Saas-Pricing-Page-2", "designer": "Cansaas", "likes": "88", "views": "30.2k"},
    {"title": "Saas pricing page table UI Subpages", "tags": "clean ui figma minimal pricing plans pricing pricing page pricing table saas sub pages table template web design webflow website", "url": "/shots/22033735-Saas-pricing-page-table-UI-Subpages", "designer": "Ranu Hasan", "likes": "98", "views": "42.3k"},
    {"title": "Dark Mode SaaS Pricing Page", "tags": "component dark darkmode darkui design interface landing minimal product saas ui uiux ux web", "url": "/shots/26838556-Dark-Mode-SaaS-Pricing-Page", "designer": "heymmd", "likes": "4", "views": "1.6k"},
    {"title": "Offsitee SaaS Pricing Page UI Design", "tags": "clean ui landing page modern ui pricing comparison pricing page pricing table ui saas design saas interface saas landing page saas pricing page subscription plans ui web design", "url": "/shots/26765689-Offsitee-SaaS-Pricing-Page-UI-Design", "designer": "Bhavik Dobariya", "likes": "11", "views": "7.2k"},
    {"title": "SaaS Pricing Pages Design", "tags": "landing page pricing pricing card pricing design pricing pages pricing section pricing ui saas saas pricing ui web design website design", "url": "/shots/27024867-SaaS-Pricing-Pages-Design", "designer": "Ragip Diler", "likes": "13", "views": "3.3k"},
]

ingest_shots(shots, "pricing-page-saas")
