"""
Apply vision analysis results to patterns.json.
This script reads analysis results from data/vision_results.json 
(generated by the batch vision pipeline) and enriches patterns.
"""
import json
from pathlib import Path
from collections import Counter

BASE_DIR = Path(__file__).resolve().parent.parent
PATTERNS_PATH = BASE_DIR / "data" / "patterns.json"
RESULTS_PATH = BASE_DIR / "data" / "vision_results.json"
MODEL_OUTPUT_PATH = BASE_DIR / "data" / "vision_model.json"

COMPONENT_PROPS = {
    "Navigation Bar": {"name": "NavBar", "props": ["items", "activeItem", "logo", "onNavigate"]},
    "Sidebar": {"name": "Sidebar", "props": ["items", "collapsed", "activeItem", "onToggle"]},
    "Search Bar": {"name": "SearchInput", "props": ["placeholder", "value", "onChange", "onSubmit"]},
    "Button": {"name": "Button", "props": ["variant", "size", "onClick", "disabled", "loading"]},
    "Card": {"name": "Card", "props": ["title", "description", "image", "actions", "footer"]},
    "Data Table": {"name": "DataTable", "props": ["columns", "data", "sortable", "filterable", "pagination"]},
    "Form": {"name": "FormField", "props": ["label", "type", "placeholder", "value", "onChange", "error"]},
    "Dropdown": {"name": "Select", "props": ["options", "value", "onChange", "placeholder"]},
    "Modal": {"name": "Dialog", "props": ["open", "onClose", "title", "description"]},
    "Tabs": {"name": "Tabs", "props": ["items", "activeTab", "onChange", "variant"]},
    "Chart": {"name": "Chart", "props": ["type", "data", "options", "responsive"]},
    "Avatar": {"name": "Avatar", "props": ["src", "alt", "size", "fallback"]},
    "Badge": {"name": "Badge", "props": ["count", "variant", "dot"]},
    "Progress Bar": {"name": "Progress", "props": ["value", "max", "label"]},
    "Hero Section": {"name": "Hero", "props": ["title", "subtitle", "cta", "background"]},
    "Footer": {"name": "Footer", "props": ["links", "copyright", "social"]},
    "Pricing Table": {"name": "PricingCard", "props": ["plan", "price", "features", "cta", "popular"]},
    "Image Gallery": {"name": "Gallery", "props": ["images", "columns", "lightbox"]},
    "Testimonials": {"name": "Testimonial", "props": ["quote", "author", "role", "avatar"]},
    "Stats": {"name": "StatCard", "props": ["label", "value", "change", "trend"]},
    "Timeline": {"name": "Timeline", "props": ["items", "orientation"]},
    "Toggle": {"name": "Switch", "props": ["checked", "onChange", "label"]},
    "Icon Grid": {"name": "FeatureGrid", "props": ["items", "columns", "iconSize"]},
    "Chat": {"name": "ChatMessage", "props": ["content", "sender", "timestamp", "avatar"]},
    "Tooltip": {"name": "Tooltip", "props": ["content", "trigger", "position"]},
}


def apply_results():
    with open(PATTERNS_PATH) as f:
        patterns = json.load(f)
    
    with open(RESULTS_PATH) as f:
        results = json.load(f)
    
    # Build lookup by image_url
    pattern_map = {}
    for i, p in enumerate(patterns):
        if p.get("image_url"):
            pattern_map[p["image_url"]] = i
    
    enriched = 0
    
    for image_key, analysis in results.items():
        if image_key not in pattern_map:
            continue
        
        idx = pattern_map[image_key]
        
        if analysis.get("ui_elements"):
            patterns[idx]["ui_elements"] = analysis["ui_elements"]
        
        if analysis.get("visual_style"):
            patterns[idx]["visual_style"] = analysis["visual_style"]
        
        if analysis.get("page_type"):
            current = patterns[idx].get("page_type", "")
            if not current or current in ("Unknown", "Web Page", "Screenshot", ""):
                patterns[idx]["page_type"] = analysis["page_type"]
        
        if analysis.get("layout_type"):
            patterns[idx]["layout_type"] = analysis["layout_type"]
        
        if analysis.get("color_mode"):
            patterns[idx]["color_mode"] = analysis["color_mode"]
        
        # Component hints from detected elements
        hints = []
        for el in analysis.get("ui_elements", [])[:8]:
            if el in COMPONENT_PROPS:
                hints.append(COMPONENT_PROPS[el])
        if hints:
            patterns[idx]["component_hints"] = hints
        
        # Quality score
        if analysis.get("quality_score"):
            old_q = patterns[idx].get("quality_score", 5.0)
            vision_q = float(analysis["quality_score"])
            new_q = round(old_q * 0.3 + vision_q * 0.7, 1)
            metadata_bonus = min(1.5, len(analysis.get("ui_elements", [])) * 0.1)
            patterns[idx]["quality_score"] = round(min(10.0, new_q + metadata_bonus), 1)
        
        tags = patterns[idx].get("tags", [])
        if "vision-enriched" not in tags:
            tags.append("vision-enriched")
        patterns[idx]["tags"] = tags
        
        enriched += 1
    
    # Sort by quality
    patterns.sort(key=lambda p: p.get("quality_score", 0), reverse=True)
    
    with open(PATTERNS_PATH, "w") as f:
        json.dump(patterns, f, indent=2)
    
    # Stats
    print(f"Enriched {enriched} patterns")
    
    enriched_p = [p for p in patterns if "vision-enriched" in p.get("tags", [])]
    avg_el = sum(len(p.get("ui_elements", [])) for p in enriched_p) / max(1, len(enriched_p))
    avg_q = sum(p.get("quality_score", 0) for p in enriched_p) / max(1, len(enriched_p))
    
    all_elements = Counter()
    for p in enriched_p:
        for el in p.get("ui_elements", []):
            all_elements[el] += 1
    
    print(f"Avg elements: {avg_el:.1f}, Avg quality: {avg_q:.1f}")
    print(f"Top elements: {all_elements.most_common(10)}")


if __name__ == "__main__":
    apply_results()
